/*
SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
SPDX-License-Identifier: MIT
*/

import { File } from "./file";
import { IRelationship } from "./relationship";

export class SoftwareBillOfMaterials {
  readonly SPDXID = "SPDXRef-DOCUMENT";
  readonly spdxVersion = "SPDX-2.3";
  name: string;
  readonly documentNamespace = "http://spdx.org/spdxdocs/spdx-v2.3-45eae250-b782-46dd-9723-62ec3bed2a7c";
  readonly dataLicense = "CC0-1.0";
  creationInfo: {
    comment: string,
    created: string,
    creators: string[]
  };
  relationships: IRelationship[] = [];
  files: File[] = [];

  constructor(name: string, tool: string) {
    this.name = name;
    this.creationInfo = {
      comment: `Generated by ${tool}`,
      created: new Date().toISOString(),
      creators: [`Tool: ${tool}`]
    }
  }

  async addFile(file: string) {
    const spdxFile = await File.fromFile(file)
    this.files.push(spdxFile);
    this.relationships.push({
      spdxElementId: this.SPDXID,
      relationshipType: "DESCRIBES",
      relatedSpdxElement: spdxFile.SPDXID
    })
  }
}
